export enum USER_STATUS {
  'ACTIVE' = 'ACTIVE',
  'INACTIVE' = 'INACTIVE',
  'BLOCKED' = 'BLOCKED',
  'DELETED' = 'DELETED',
}

export enum USER_COUNTRY {
  'AFGHANISTAN' = 'AFGHANISTAN',
  'INDIA' = 'INDIA',
  'CHINA' = 'CHINA',
  'UNITED_STATES' = 'UNITED_STATES',
  'CANADA' = 'CANADA',
  'AUSTRALIA' = 'AUSTRALIA',
}

export enum USER_GENDER {
  'MALE' = 'MALE',
  'FEMALE' = 'FEMALE',
  'OTHER' = 'OTHER',
}
